import Head from "next/head";
import Carousel from "@/components/Carousel";
import Collection from "@/components/Collection";
import GalacticMap from "@/components/GalacticMap";
import Archives from "@/components/Archives";
import DefendersArcade from "@/components/DefendersArcade";
import CollectionsPage from "@/components/CollectionsPage";
import InteractiveLore from "@/components/InteractiveLore"
import HolderProfile from "@/components/HolderProfile"
export default function Home() {
  return (
    <>
      <Head>
        <title>Super Space defenders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Carousel />
      <Collection/>
      <GalacticMap />
      <Archives />

      <InteractiveLore /> 
      <DefendersArcade/>
      <HolderProfile/>
      <CollectionsPage />
    </>
  );
}
