import Head from "next/head";
import Carousel from "@/components/Index/Carousel";
import Collection from "@/components/Index/Collection";
import GalacticMap from "@/components/Index/GalacticMap";
import Archives from "@/components/Index/Archives";
import Arcade from "@/components/Index/Arcade";
import RetroMachines from "@/components/Index/RetroMachines";
import Footer from "@/components/Index/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Super Space defenders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Carousel />
      <RetroMachines />
      <Collection />
      <GalacticMap />
      <Arcade />
      <Archives />
      <Footer />
    </>
  );
}

